NAME = Form

FLAGS = -Wall -Wextra -Werror -std=c++98

CC = c++


SRCS = main.cpp Bureaucrat.cpp AForm.cpp ShrubberyCreationForm.cpp RobotomyRequestForm.cpp PresidentialPardonForm.cpp Intern.cpp


all : $(NAME)

$(NAME) : $(SRCS)
	@$(CC) $(FLAGS) $(SRCS) -o $@
	@tput setaf 3; echo "                  _____                   _______                   _____                    _____          "
	@tput setaf 3; echo "                 /\    \                 /::\    \                 /\    \                  /\    \          "
	@tput setaf 3; echo "                /::\    \               /::::\    \               /::\    \                /::\____\         "
	@tput setaf 3; echo "               /::::\    \             /::::::\    \             /::::\    \              /::::|   |         "
	@tput setaf 3; echo "              /::::::\    \           /::::::::\    \           /::::::\    \            /:::::|   |         "
	@tput setaf 3; echo "             /:::/\:::\    \         /:::/~~\:::\    \         /:::/\:::\    \          /::::::|   |         "
	@tput setaf 3; echo "            /:::/__\:::\    \       /:::/    \:::\    \       /:::/__\:::\    \        /:::/|::|   |         "
	@tput setaf 3; echo "           /::::\   \:::\    \     /:::/    / \:::\    \     /::::\   \:::\    \      /:::/ |::|   |         "
	@tput setaf 3; echo "          /::::::\   \:::\    \   /:::/____/   \:::\____\   /::::::\   \:::\    \    /:::/  |::|___|______   "
	@tput setaf 3; echo "         /:::/\:::\   \:::\    \ |:::|    |     |:::|    | /:::/\:::\   \:::\____\  /:::/   |::::::::\    \  "
	@tput setaf 3; echo "        /:::/  \:::\   \:::\____\|:::|____|     |:::|    |/:::/  \:::\   \:::|    |/:::/    |:::::::::\____\ "
	@tput setaf 3; echo "        \::/    \:::\   \::/    / \:::\    \   /:::/    / \::/   |::::\  /:::|____|\::/    / ~~~~~/:::/    / "
	@tput setaf 3; echo "         \/____/ \:::\   \/____/   \:::\    \ /:::/    /   \/____|:::::\/:::/    /  \/____/      /:::/    /  "
	@tput setaf 3; echo "                  \:::\    \        \:::\    /:::/    /          |:::::::::/    /               /:::/    /   "
	@tput setaf 3; echo "                   \:::\____\        \:::\__/:::/    /           |::|\::::/    /               /:::/    /    "
	@tput setaf 3; echo "                    \::/    /         \::::::::/    /            |::| \::/____/               /:::/    /     "
	@tput setaf 3; echo "                     \/____/           \::::::/    /             |::|  ~|                    /:::/    /      "
	@tput setaf 3; echo "                                        \::::/    /              |::|   |                   /:::/    /       "
	@tput setaf 3; echo "                                         \::/____/               \::|   |                  /:::/    /        "
	@tput setaf 3; echo "                                          ~~                      \:|   |                  \::/    /         "
	@tput setaf 3; echo "                                                                   \|___|                   \/____/          "
	@tput setaf 3; echo "                                                                                      "
	@tput setaf 3; echo "                                                                               excutable file is ready .     "


clean : 
	@rm -rf $(NAME)
	@tput setaf 1; echo "excutable file removed ."
fclean : clean
	@rm -rf *_shrubbery
re : fclean all